// source: MessageService.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.ru.miet.example.grpc.chat.service.GetMessagesRequest', null, global);
goog.exportSymbol('proto.ru.miet.example.grpc.chat.service.GetMessagesResponse', null, global);
goog.exportSymbol('proto.ru.miet.example.grpc.chat.service.SendMessageRequest', null, global);
goog.exportSymbol('proto.ru.miet.example.grpc.chat.service.SendMessageResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ru.miet.example.grpc.chat.service.SendMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.miet.example.grpc.chat.service.SendMessageRequest.displayName = 'proto.ru.miet.example.grpc.chat.service.SendMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ru.miet.example.grpc.chat.service.SendMessageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.miet.example.grpc.chat.service.SendMessageResponse.displayName = 'proto.ru.miet.example.grpc.chat.service.SendMessageResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ru.miet.example.grpc.chat.service.GetMessagesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.displayName = 'proto.ru.miet.example.grpc.chat.service.GetMessagesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.repeatedFields_, null);
};
goog.inherits(proto.ru.miet.example.grpc.chat.service.GetMessagesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.displayName = 'proto.ru.miet.example.grpc.chat.service.GetMessagesResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.miet.example.grpc.chat.service.SendMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    token: jspb.Message.getFieldWithDefault(msg, 1, ""),
    text: jspb.Message.getFieldWithDefault(msg, 2, ""),
    chatid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    recipientid: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.miet.example.grpc.chat.service.SendMessageRequest;
  return proto.ru.miet.example.grpc.chat.service.SendMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setChatid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRecipientid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.miet.example.grpc.chat.service.SendMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getChatid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getRecipientid();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
};


/**
 * optional string token = 1;
 * @return {string}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest} returns this
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string text = 2;
 * @return {string}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest} returns this
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint64 chatId = 3;
 * @return {number}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.getChatid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest} returns this
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.setChatid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 recipientId = 4;
 * @return {number}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.getRecipientid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageRequest} returns this
 */
proto.ru.miet.example.grpc.chat.service.SendMessageRequest.prototype.setRecipientid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.miet.example.grpc.chat.service.SendMessageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    statuscode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    statusdesc: jspb.Message.getFieldWithDefault(msg, 2, ""),
    message: (f = msg.getMessage()) && common_pb.Message.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.miet.example.grpc.chat.service.SendMessageResponse;
  return proto.ru.miet.example.grpc.chat.service.SendMessageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ru.miet.example.grpc.chat.service.StatusCode} */ (reader.readEnum());
      msg.setStatuscode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatusdesc(value);
      break;
    case 3:
      var value = new common_pb.Message;
      reader.readMessage(value,common_pb.Message.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.miet.example.grpc.chat.service.SendMessageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatuscode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStatusdesc();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_pb.Message.serializeBinaryToWriter
    );
  }
};


/**
 * optional StatusCode statusCode = 1;
 * @return {!proto.ru.miet.example.grpc.chat.service.StatusCode}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.getStatuscode = function() {
  return /** @type {!proto.ru.miet.example.grpc.chat.service.StatusCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ru.miet.example.grpc.chat.service.StatusCode} value
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse} returns this
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.setStatuscode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string statusDesc = 2;
 * @return {string}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.getStatusdesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse} returns this
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.setStatusdesc = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Message message = 3;
 * @return {?proto.ru.miet.example.grpc.chat.service.Message}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.getMessage = function() {
  return /** @type{?proto.ru.miet.example.grpc.chat.service.Message} */ (
    jspb.Message.getWrapperField(this, common_pb.Message, 3));
};


/**
 * @param {?proto.ru.miet.example.grpc.chat.service.Message|undefined} value
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse} returns this
*/
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ru.miet.example.grpc.chat.service.SendMessageResponse} returns this
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.miet.example.grpc.chat.service.SendMessageResponse.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    token: jspb.Message.getFieldWithDefault(msg, 1, ""),
    chatid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageparams: (f = msg.getPageparams()) && common_pb.PageParams.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.miet.example.grpc.chat.service.GetMessagesRequest;
  return proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setChatid(value);
      break;
    case 3:
      var value = new common_pb.PageParams;
      reader.readMessage(value,common_pb.PageParams.deserializeBinaryFromReader);
      msg.setPageparams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChatid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getPageparams();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_pb.PageParams.serializeBinaryToWriter
    );
  }
};


/**
 * optional string token = 1;
 * @return {string}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest} returns this
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 chatId = 2;
 * @return {number}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.getChatid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest} returns this
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.setChatid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional PageParams pageParams = 3;
 * @return {?proto.ru.miet.example.grpc.chat.service.PageParams}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.getPageparams = function() {
  return /** @type{?proto.ru.miet.example.grpc.chat.service.PageParams} */ (
    jspb.Message.getWrapperField(this, common_pb.PageParams, 3));
};


/**
 * @param {?proto.ru.miet.example.grpc.chat.service.PageParams|undefined} value
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest} returns this
*/
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.setPageparams = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesRequest} returns this
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.clearPageparams = function() {
  return this.setPageparams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesRequest.prototype.hasPageparams = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    statuscode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    statusdesc: jspb.Message.getFieldWithDefault(msg, 2, ""),
    chatid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    messagesList: jspb.Message.toObjectList(msg.getMessagesList(),
    common_pb.Message.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ru.miet.example.grpc.chat.service.GetMessagesResponse;
  return proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ru.miet.example.grpc.chat.service.StatusCode} */ (reader.readEnum());
      msg.setStatuscode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatusdesc(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setChatid(value);
      break;
    case 4:
      var value = new common_pb.Message;
      reader.readMessage(value,common_pb.Message.deserializeBinaryFromReader);
      msg.addMessages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatuscode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStatusdesc();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getChatid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getMessagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      common_pb.Message.serializeBinaryToWriter
    );
  }
};


/**
 * optional StatusCode statusCode = 1;
 * @return {!proto.ru.miet.example.grpc.chat.service.StatusCode}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.getStatuscode = function() {
  return /** @type {!proto.ru.miet.example.grpc.chat.service.StatusCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ru.miet.example.grpc.chat.service.StatusCode} value
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse} returns this
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.setStatuscode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string statusDesc = 2;
 * @return {string}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.getStatusdesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse} returns this
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.setStatusdesc = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint64 chatId = 3;
 * @return {number}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.getChatid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse} returns this
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.setChatid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated Message messages = 4;
 * @return {!Array<!proto.ru.miet.example.grpc.chat.service.Message>}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.getMessagesList = function() {
  return /** @type{!Array<!proto.ru.miet.example.grpc.chat.service.Message>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_pb.Message, 4));
};


/**
 * @param {!Array<!proto.ru.miet.example.grpc.chat.service.Message>} value
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse} returns this
*/
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.setMessagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ru.miet.example.grpc.chat.service.Message=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ru.miet.example.grpc.chat.service.Message}
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.addMessages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ru.miet.example.grpc.chat.service.Message, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ru.miet.example.grpc.chat.service.GetMessagesResponse} returns this
 */
proto.ru.miet.example.grpc.chat.service.GetMessagesResponse.prototype.clearMessagesList = function() {
  return this.setMessagesList([]);
};


goog.object.extend(exports, proto.ru.miet.example.grpc.chat.service);
