version: "3.3"

services:

  db:
    container_name: chat-postgres
    image: postgres:13-alpine
    env_file:
      - docker-config/chat-postgres.env
    volumes:
      - chat-postgres-data:/var/lib/postgresql/data/
      - ./docker-config/sql/:/docker-entrypoint-initdb.d/
    ports:
      - "127.0.0.1:5432:5432"

  chat-backend:
    container_name: chat-backend
    image: dmshorokhov/example-miet-chat-server:0.0.2
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/grpc-chat?schema=chat
      GRPC_SERVER_PORT: 7654
      LOGGING_LEVEL_ROOT: DEBUG
    ports:
      - "127.0.0.1:7654:7654"

  proxy:
    container_name: envoy
    image: envoyproxy/envoy-alpine:v1.9.0
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./docker-config/envoy.yaml:/etc/envoy/envoy.yaml

volumes:
  chat-postgres-data:
